/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import auth.Auth;
import dao_conexion.dao_personal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import models.personal;

/**
 *
 * @author Lenovo
 */
public class jfListadoPersonal extends javax.swing.JFrame {

    Statement stmt = null;
    ResultSet rs = null;
    private final Auth SQL = new Auth();
    private final Connection conn = SQL.conectarMySQL();
    dao_personal per = new dao_personal();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-M-d");
    java.util.Date fecha = new Date();
    long d = fecha.getTime();
    java.sql.Date fechaa = new java.sql.Date(d);

    /**
     * Creates new form jfListadoPersonal
     */
    public jfListadoPersonal() {
        initComponents();
        jLabel_id.setVisible(false);
        per.llenarTabla(jTable1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_salario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_apellidos = new javax.swing.JTextField();
        jLabel_contrata = new javax.swing.JLabel();
        jTextField_ci = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jTextFiel_ocupacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_contrata = new javax.swing.JComboBox<>();
        jLabel_tiempo_contrata = new javax.swing.JLabel();
        jLabel_mes = new javax.swing.JLabel();
        jSpinnerSalario = new javax.swing.JSpinner();
        jSpinnerSalarioContrata = new javax.swing.JSpinner();
        jSpinnerTiempoContrata = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerEdad = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButton_insertar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldBuscr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_ci = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listao de Personal");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Formulario"));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ocupación");

        jLabel_salario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_salario.setText("Salario");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Apellidos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Contrata");

        jTextField_apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_contrata.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_contrata.setText("Salario Contrata");
        jLabel_contrata.setEnabled(false);

        jTextField_ci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_ci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ciKeyPressed(evt);
            }
        });

        jTextField_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jTextFiel_ocupacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CI");

        jComboBox_contrata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        jComboBox_contrata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_contrataActionPerformed(evt);
            }
        });

        jLabel_tiempo_contrata.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_tiempo_contrata.setText("Tiempo contrata");
        jLabel_tiempo_contrata.setEnabled(false);

        jLabel_mes.setText("Mes");
        jLabel_mes.setEnabled(false);

        jSpinnerSalarioContrata.setEnabled(false);

        jSpinnerTiempoContrata.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Sexo");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        jLabel6.setText("Edad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_apellidos)
                    .addComponent(jTextField_nombre)
                    .addComponent(jTextField_ci)
                    .addComponent(jTextFiel_ocupacion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxSexo, 0, 95, Short.MAX_VALUE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_salario)
                            .addComponent(jLabel_contrata)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerSalarioContrata, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerSalario)
                            .addComponent(jComboBox_contrata, 0, 68, Short.MAX_VALUE)
                            .addComponent(jSpinnerEdad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_tiempo_contrata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerTiempoContrata, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_ci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_contrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_salario)
                    .addComponent(jSpinnerSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerSalarioContrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_contrata))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFiel_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tiempo_contrata)
                    .addComponent(jSpinnerTiempoContrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_mes))
                .addGap(57, 57, 57))
        );

        jButton_insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        jButton_insertar.setText("insertar");
        jButton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertarActionPerformed(evt);
            }
        });

        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Exit.png"))); // NOI18N
        jButton_cancelar.setText("Cancelar");

        jLabel_id.setText("ID  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_insertar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jButton_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_id)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_eliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CI", "Nombre", "Ocupacion", "Contrata", "Salario", "Salario Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextFieldBuscr.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextFieldBuscr.setText("Buscar");
        jTextFieldBuscr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscrMouseClicked(evt);
            }
        });
        jTextFieldBuscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscrActionPerformed(evt);
            }
        });
        jTextFieldBuscr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscrKeyPressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N

        jLabel_ci.setText("970926262666");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(756, 756, 756)
                        .addComponent(jLabel_ci)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldBuscr, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldBuscr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ci)
                        .addGap(1, 1, 1)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_contrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_contrataActionPerformed
        // TODO add your handling code here:

        if (jComboBox_contrata.getSelectedItem().equals("SI")) {
            jSpinnerSalarioContrata.setEnabled(true);
            jLabel_contrata.setEnabled(true);
            jLabel_tiempo_contrata.setEnabled(true);
            jSpinnerTiempoContrata.setEnabled(true);
            jLabel_mes.setEnabled(true);
            jSpinnerSalario.setEnabled(false);
            jLabel_salario.setEnabled(false);
        } else {
            jSpinnerSalarioContrata.setEnabled(false);
            jLabel_contrata.setEnabled(false);
            jLabel_tiempo_contrata.setEnabled(false);
            jSpinnerTiempoContrata.setEnabled(false);
            jLabel_mes.setEnabled(false);
            jSpinnerSalario.setEnabled(true);
            jLabel_salario.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_contrataActionPerformed

    private void jButton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertarActionPerformed
        // TODO add your handling code here:
        String ci = jTextField_ci.getText();
        String nombre = jTextField_nombre.getText();
        String apellidos = jTextField_apellidos.getText();
        String ocupacion = jTextFiel_ocupacion.getText();
        String contrata = jComboBox_contrata.getSelectedItem().toString();
        String sexo = jComboBoxSexo.getSelectedItem().toString();
        int salario = (int) jSpinnerSalario.getValue();
        int edad = (int) jSpinnerEdad.getValue();
        int salario_contrata = (int) jSpinnerSalarioContrata.getValue();
        int tiempo_contrata = (int) jSpinnerTiempoContrata.getValue();

        if (ValidarCi(ci)) {
            if (per.Existe(ci) == 0) {
                if (jComboBox_contrata.getSelectedItem().equals("SI")) {
                    personal p = new personal(WIDTH, ci, nombre, sexo, edad, apellidos, ocupacion, contrata, 0, salario_contrata, tiempo_contrata);
                    per.insertar(p);
                    per.llenarTabla(jTable1);

                } else {
                    personal p = new personal(WIDTH, ci, nombre, sexo, edad, apellidos, ocupacion, contrata, salario, 0, 0);
                    per.insertar(p);
                    per.llenarTabla(jTable1);
                }
            } else {
                Util.Util.mostrarError(rootPane, "Ya existe un trabajdor con el número de carnet " + ci);
            }
        } else {
            Util.Util.mostrarError(rootPane, "verifique bien el número de carnet");
        }


    }//GEN-LAST:event_jButton_insertarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int Fila = jTable1.getSelectedRow();
        String codigo = jTable1.getValueAt(Fila, 1).toString();

        try {
            PreparedStatement ps = conn.prepareStatement("SELECT\n"
                    + "personal.id,\n"
                    + "personal.ci,\n"
                    + "personal.nombre,\n"
                    + "personal.apellidos,\n"
                    + "personal.sexo,\n"
                    + "personal.edad,\n"
                    + "personal.ocupacion,\n"
                    + "personal.contrata,\n"
                    + "personal.salario,\n"
                    + "personal.salario_contrata,\n"
                    + "personal.tiempo_contrata\n"
                    + "FROM\n"
                    + "personal where ci=?");

            ps.setString(1, codigo);
            rs = ps.executeQuery();
            while (rs.next()) {
                jLabel_id.setText(rs.getString("id"));
                jTextField_ci.setText(rs.getString("ci"));
                jTextField_nombre.setText(rs.getString("nombre"));
                jTextField_apellidos.setText(rs.getString("apellidos"));
                jComboBoxSexo.setSelectedItem(rs.getString("sexo"));
                jSpinnerEdad.setValue(rs.getInt("edad"));
                jTextFiel_ocupacion.setText(rs.getString("ocupacion"));
                jComboBox_contrata.setSelectedItem(rs.getString("contrata"));
                jSpinnerSalario.setValue(rs.getInt("salario"));
                jSpinnerSalarioContrata.setValue(rs.getInt("salario_contrata"));
                jSpinnerTiempoContrata.setValue(rs.getInt("tiempo_contrata"));

            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:

        if (jTable1.getSelectedRow() != -1) {
            String ci = jTextField_ci.getText();
            String nombre = jTextField_nombre.getText();
            String apellidos = jTextField_apellidos.getText();
            String ocupacion = jTextFiel_ocupacion.getText();
            String contrata = jComboBox_contrata.getSelectedItem().toString();

            int salario = (int) jSpinnerSalario.getValue();
            int edad = (int) jSpinnerEdad.getValue();
            String sexo = jComboBoxSexo.getSelectedItem().toString();
            int salario_contrata = (int) jSpinnerSalarioContrata.getValue();
            int tiempo_contrata = (int) jSpinnerTiempoContrata.getValue();
            int id = Integer.parseInt(jLabel_id.getText());

            if (ValidarCi(ci)) {
                if (per.Existe(ci) == 0) {
                    if (jComboBox_contrata.getSelectedItem().equals("SI")) {
                        personal p = new personal(WIDTH, ci, nombre, sexo, edad, apellidos, ocupacion, contrata, 0, salario_contrata, tiempo_contrata);
                        per.actualizar(p);
                        per.llenarTabla(jTable1);

                    } else {
                        personal p = new personal(id);
                        per.actualizar(p);
                        per.llenarTabla(jTable1);
                    }
                } else {
                    Util.Util.mostrarError(rootPane, "Ya existe un trabajdor con el número de carnet " + ci);
                }
            } else {
                Util.Util.mostrarError(rootPane, "verifique bien el número de carnet");
            }

        } else {
            Util.Util.mostrarError(rootPane, "Debe Selecciona una Fila");
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            int valor = Util.Util.confirmarInformacion(rootPane, "Elimnar ", "Seguro que desea eliminar");
            if (valor == 0) {
                int id = Integer.parseInt(jLabel_id.getText());
                personal p = new personal(id);
                per.eliminar(p);
                per.llenarTabla(jTable1);

            } else {
                Util.Util.mostrarError(rootPane, "Debe Selecionar una fila");
            }
        }


    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jTextFieldBuscrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscrMouseClicked
        // TODO add your handling code here:
        jTextFieldBuscr.setText("");
    }//GEN-LAST:event_jTextFieldBuscrMouseClicked

    private void jTextFieldBuscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscrActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextFieldBuscrActionPerformed

    private void jTextFieldBuscrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscrKeyPressed
        // TODO add your handling code here:
        per.Buscar(jTable1, jTextFieldBuscr.getText());
    }//GEN-LAST:event_jTextFieldBuscrKeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_formMouseClicked

    private void jTextField_ciKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ciKeyPressed


    }//GEN-LAST:event_jTextField_ciKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfListadoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfListadoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfListadoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfListadoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfListadoPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_insertar;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBox_contrata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_ci;
    private javax.swing.JLabel jLabel_contrata;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_mes;
    private javax.swing.JLabel jLabel_salario;
    private javax.swing.JLabel jLabel_tiempo_contrata;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerEdad;
    private javax.swing.JSpinner jSpinnerSalario;
    private javax.swing.JSpinner jSpinnerSalarioContrata;
    private javax.swing.JSpinner jSpinnerTiempoContrata;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFiel_ocupacion;
    private javax.swing.JTextField jTextFieldBuscr;
    private javax.swing.JTextField jTextField_apellidos;
    private javax.swing.JTextField jTextField_ci;
    private javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables
public void limpiar() {
        jTextField_ci.setText("");
        jTextField_nombre.setText("");
        jTextField_apellidos.setText("");
        jTextFiel_ocupacion.setText("");
        jSpinnerSalario.setValue(0);
        jSpinnerSalarioContrata.setValue(0);
        jSpinnerTiempoContrata.setValue(0);
    }

    public static boolean ValidarCi(String ci) {
        int cont = 0;
        for (int i = 0; i < ci.length(); i++) {
            if (ci.charAt(i) >= '0' && ci.charAt(i) <= '9') {
                cont++;
            }
        }
        if (cont == 11) {
            String mesS = ci.substring(2, 4);
            String diaS = ci.substring(4, 6);
            int dia = Integer.parseInt(diaS);
            int mes = Integer.parseInt(mesS);
            int[] mes_mas_dias = {1, 3, 5, 7, 8, 10, 12};
            int[] mes_menos_dias = {4, 6, 9, 11};

            if (mes == 2 && dia >= 1 && dia <= 29) {
                return true;
            }
            for (int mes_mas_dia : mes_mas_dias) {
                if (mes == mes_mas_dia && (dia >= 1 && dia <= 31)) {
                    return true;
                }
            }
            for (int mes_menos_dia : mes_menos_dias) {
                if (mes == mes_menos_dia && (dia >= 1 && dia <= 30)) {
                    return true;
                }
            }

        }
        return false;
    }

}
