/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import auth.Auth;
import dao_conexion.dao_producion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import models.consumo;
import models.producion;

/**
 *
 * @author Lenovo
 */
public class jfListadoProduccion extends javax.swing.JFrame {

    Statement stmt = null;
    ResultSet rs = null;
    private final Auth SQL = new Auth();
    private final Connection conn = SQL.conectarMySQL();

    dao_conexion.dao_producion pro = new dao_producion();

    /**
     * Creates new form jfListadoProduccion
     */
    public jfListadoProduccion() {
        initComponents();
        pro.llenarTabla(jTable1);
        ajustarTablaConsumo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_normaProduccion = new javax.swing.JLabel();
        jLabel_refino = new javax.swing.JLabel();
        jLabel_azucarTotal = new javax.swing.JLabel();
        jLabel_mielProducioda = new javax.swing.JLabel();
        jLabel_insumo_ageno = new javax.swing.JLabel();
        jLabel_refinoProcesar = new javax.swing.JLabel();
        jLabel_sacos = new javax.swing.JLabel();
        jLabel_azucarPizarra = new javax.swing.JLabel();
        jSpinnerSacos = new javax.swing.JSpinner();
        jSpinnerAzucarPizarra = new javax.swing.JSpinner();
        jSpinnerNorma = new javax.swing.JSpinner();
        jSpinnerRefino = new javax.swing.JSpinner();
        jSpinnerMielProducida = new javax.swing.JSpinner();
        jSpinnerInsumoAjeno = new javax.swing.JSpinner();
        jSpinnerRefinoProcesar = new javax.swing.JSpinner();
        jSpinnerAzucarTotal = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButton_insertar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Producción");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Formulario"));
        jPanel1.setToolTipText("");
        jPanel1.setFocusCycleRoot(true);

        jLabel_normaProduccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_normaProduccion.setText("Norma de produccion");

        jLabel_refino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_refino.setText("TM Refino");

        jLabel_azucarTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_azucarTotal.setText("Azúcar total");

        jLabel_mielProducioda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_mielProducioda.setText("Miel Producida");

        jLabel_insumo_ageno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_insumo_ageno.setText("Insumo Ajeno");

        jLabel_refinoProcesar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_refinoProcesar.setText("Refino Procesar");

        jLabel_sacos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_sacos.setText("Sacos");

        jLabel_azucarPizarra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_azucarPizarra.setText("TM de Azúcar Pizarra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_refino)
                    .addComponent(jLabel_normaProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_sacos)
                    .addComponent(jLabel_azucarPizarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerNorma, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jSpinnerAzucarPizarra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerSacos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerRefino))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_mielProducioda)
                        .addComponent(jLabel_insumo_ageno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_refinoProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_azucarTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerAzucarTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jSpinnerRefinoProcesar)
                    .addComponent(jSpinnerInsumoAjeno)
                    .addComponent(jSpinnerMielProducida))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sacos)
                    .addComponent(jLabel_mielProducioda)
                    .addComponent(jSpinnerSacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMielProducida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_azucarPizarra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_insumo_ageno)
                    .addComponent(jSpinnerAzucarPizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerInsumoAjeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_normaProduccion)
                    .addComponent(jLabel_refinoProcesar)
                    .addComponent(jSpinnerRefinoProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNorma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_refino)
                    .addComponent(jLabel_azucarTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAzucarTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerRefino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jButton_insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        jButton_insertar.setText("Insertar ");
        jButton_insertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_insertarMouseClicked(evt);
            }
        });
        jButton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertarActionPerformed(evt);
            }
        });

        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Exit.png"))); // NOI18N
        jButton_cancelar.setText("Cancelar");

        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        jLabel_id.setText("Id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_insertar)
                    .addComponent(jButton_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_id)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_id)
                        .addGap(50, 50, 50))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TM De Azúcar Pizarra", "Norma de Producción", "TM Refino", "Total de Azúcar", "Miel Producida", "Insumo Ajeno", "Refino Procesar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_insertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_insertarMouseClicked
        int sacos = (int) jSpinnerSacos.getValue();
        int azucarPizarra = (int) jSpinnerAzucarPizarra.getValue();
        int normaProduccion = (int) jSpinnerNorma.getValue();
        int refino = (int) jSpinnerRefino.getValue();
        int mielProducida = (int) jSpinnerMielProducida.getValue();
        int insumoAjeno = (int) jSpinnerInsumoAjeno.getValue();
        int refinoProcesar = (int) jSpinnerRefinoProcesar.getValue();
        int azucarTotal = (int) jSpinnerAzucarTotal.getValue();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-M-d");
        java.util.Date fecha = new Date();
        long d = fecha.getTime();
        java.sql.Date fechaa = new java.sql.Date(d);
        if (pro.existe(fechaa) == 0) {
            producion p = new producion(WIDTH, mielProducida, sacos, azucarPizarra, normaProduccion, refino, azucarTotal, insumoAjeno, refinoProcesar, fechaa);
            pro.insertar(p);
            limpiar();
            pro.llenarTabla(jTable1);

        } else {
            Util.Util.mostrarError(rootPane, "Solo 1 por dia");
        }
    }//GEN-LAST:event_jButton_insertarMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int Fila = jTable1.getSelectedRow();
        String codigo = jTable1.getValueAt(Fila, 9).toString();

        try {
            PreparedStatement ps = conn.prepareStatement("SELECT\n"
                    + "producion.id_producion,\n"
                    + "producion.sacos,\n"
                    + "producion.azucarPizarra,\n"
                    + "producion.norma_producion,\n"
                    + "producion.tm_refino,\n"
                    + "producion.total_azucar,\n"
                    + "producion.miel,\n"
                    + "producion.insumo_ajeno,\n"
                    + "producion.refino_a_procesar,\n"
                    + "producion.produccion_fecha\n"
                    + "FROM\n"
                    + "producion where produccion_fecha=?");

            ps.setString(1, codigo);

            rs = ps.executeQuery();
            while (rs.next()) {

                jLabel_id.setText(rs.getString("id_producion"));
                jSpinnerSacos.setValue(rs.getInt("sacos"));
                jSpinnerAzucarPizarra.setValue(rs.getInt("azucarPizarra"));
                jSpinnerNorma.setValue(rs.getInt("norma_producion"));
                jSpinnerRefino.setValue(rs.getInt("tm_refino"));
                jSpinnerMielProducida.setValue(rs.getInt("miel"));
                jSpinnerInsumoAjeno.setValue(rs.getInt("insumo_ajeno"));
                jSpinnerRefinoProcesar.setValue(rs.getInt("refino_a_procesar"));
                jSpinnerAzucarTotal.setValue(rs.getInt("total_azucar"));

            }

        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_insertarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            int id = Integer.parseInt(jLabel_id.getText());
            int valor = Util.Util.confirmarInformacion(rootPane, "Eliminar", "Desea eliminar la produción");
            if (valor == 0) {
                producion prod = new producion(id);
                pro.eliminar(prod);
                limpiar();
                pro.llenarTabla(jTable1);

            } else {
            }
        } else {
            Util.Util.mostrarError(rootPane, "Debe seleccionar una fila");
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            int sacos = (int) jSpinnerSacos.getValue();
            int azucarPizarra = (int) jSpinnerAzucarPizarra.getValue();
            int normaProduccion = (int) jSpinnerNorma.getValue();
            int refino = (int) jSpinnerRefino.getValue();
            int mielProducida = (int) jSpinnerMielProducida.getValue();
            int insumoAjeno = (int) jSpinnerInsumoAjeno.getValue();
            int refinoProcesar = (int) jSpinnerRefinoProcesar.getValue();
            int azucarTotal = (int) jSpinnerAzucarTotal.getValue();
            int id = Integer.parseInt(jLabel_id.getText());
            producion p = new producion(id, mielProducida, sacos, azucarPizarra, normaProduccion, refino, azucarTotal, insumoAjeno, refinoProcesar);

            pro.actualizar(p);

            pro.llenarTabla(jTable1);
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfListadoProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfListadoProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfListadoProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfListadoProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfListadoProduccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_azucarPizarra;
    private javax.swing.JLabel jLabel_azucarTotal;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_insumo_ageno;
    private javax.swing.JLabel jLabel_mielProducioda;
    private javax.swing.JLabel jLabel_normaProduccion;
    private javax.swing.JLabel jLabel_refino;
    private javax.swing.JLabel jLabel_refinoProcesar;
    private javax.swing.JLabel jLabel_sacos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAzucarPizarra;
    private javax.swing.JSpinner jSpinnerAzucarTotal;
    private javax.swing.JSpinner jSpinnerInsumoAjeno;
    private javax.swing.JSpinner jSpinnerMielProducida;
    private javax.swing.JSpinner jSpinnerNorma;
    private javax.swing.JSpinner jSpinnerRefino;
    private javax.swing.JSpinner jSpinnerRefinoProcesar;
    private javax.swing.JSpinner jSpinnerSacos;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void limpiar() {
        jSpinnerSacos.setValue(0);
        jSpinnerAzucarPizarra.setValue(0);
        jSpinnerNorma.setValue(0);
        jSpinnerRefino.setValue(0);
        jSpinnerMielProducida.setValue(0);
        jSpinnerInsumoAjeno.setValue(0);
        jSpinnerRefinoProcesar.setValue(0);
        jSpinnerAzucarTotal.setValue(0);
    }

    public final void ajustarTablaConsumo() {
        //columna No
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        //columna Sacos
        jTable1.getColumnModel().getColumn(1).setMinWidth(80);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
        //columna Azucar
        jTable1.getColumnModel().getColumn(2).setMinWidth(110);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(110);
        //columna Normas
        jTable1.getColumnModel().getColumn(3).setMinWidth(120);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(120);
        //columna Refino
        jTable1.getColumnModel().getColumn(4).setMinWidth(80);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(80);
        //columna Total de Azucar
        jTable1.getColumnModel().getColumn(5).setMinWidth(110);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(110);
        //columna Miel
        jTable1.getColumnModel().getColumn(6).setMinWidth(70);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(70);
        //columna Insumo Ajeno
        jTable1.getColumnModel().getColumn(7).setMinWidth(110);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(110);
        //columna Refino a Procesar
        jTable1.getColumnModel().getColumn(8).setMinWidth(100);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(100);
        //columna fecha de Produccion
        jTable1.getColumnModel().getColumn(9).setMinWidth(110);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(110);

    }

}
